package com.binance.api.client.domain.account.request

/**
 * Request object for canceling an order.
 */
class CancelOrderRequest : OrderRequest {

    var orderId: Long? = null
    var origClientOrderId: String? = null

    /**
     * Used to uniquely identify this cancel. Automatically generated by default.
     */
    var newClientOrderId: String? = null

    constructor(symbol: String, orderId: Long) : super(symbol) {
        this.orderId = orderId
    }

    constructor(symbol: String, origClientOrderId: String) : super(symbol) {
        this.origClientOrderId = origClientOrderId
    }

    fun orderId(orderId: Long?): CancelOrderRequest {
        this.orderId = orderId
        return this
    }

    fun origClientOrderId(origClientOrderId: String?): CancelOrderRequest {
        this.origClientOrderId = origClientOrderId
        return this
    }

    fun newClientOrderId(newClientOrderId: String?): CancelOrderRequest {
        this.newClientOrderId = newClientOrderId
        return this
    }

    override fun toString(): String {
        return "CancelOrderRequest(symbol=${symbol}, orderId=$orderId, origClientOrderId=$origClientOrderId, newClientOrderId=$newClientOrderId)"
    }
}